namespace :build do  
  desc "creating 1000 products per store"
  task :products => :environment do
    Store.all[0..10].each do |store|
      10000.times do |i|
        Product.create!(store_id: store.id, name: Faker::Name.name, description: Faker::Lorem.paragraph(2), price: "#{(1..500).to_a.sample}.0".to_f, quantity: "#{(1..500).to_a.sample}".to_i, featured: false, active: true)
        print "."
      end
    end
  end

  desc "1000 background task products per store" 
  task :products_task => :environment do
    a = Time.now
    Store.all[0..10].each do |store|
      10.times do |i|
        Resque.enqueue(BuildSeedProducts,store.id)
        print "."
      end
    end
    print "#{Time.now - a}"
  end

  desc "honeycantoo products" 
  task :honeycantoo => :environment do
    store = Store.find_by_path("honey-can-too")
    Product.create!(:store_id => store.id, :featured => false, :active => true, :quantity => "#{(1..500).to_a.sample}".to_i, :name => 'Wood Accordion Drying Rack', :price => 6198.to_f/100, :description => 'Honey-Can-Do DRY-01111 Wood Accordion Drying Rack, 3.6H x20W. Collapsible drying rack for air-drying clothes and saving electricity consumption. Constructed from wooden dowels and cross pieces with vinyl-coated bars. Accordion design drops and locks into place; folds flat to 3-inch width for storage. Design allow for clothes and household items to dry draped or laid flat. Measures 29-1/2 by 14-1/2-inches; 42-inches high; limited lifetime warranty', :photo_url => 'https://s3.amazonaws.com/store_engine/small/DRY-01111_450px.jpg')
    Product.create!(:store_id => store.id, :featured => false, :active => true, :quantity => "#{(1..500).to_a.sample}".to_i, :name => 'Commercial Chrome Accordion Drying Rack', :price => 14398.to_f/100, :description => 'Honey-Can-Do DRY-01234 Commercial Chrome Accordion Drying Rack, 24-ft Drying space. Commercial-grade rack for air-drying clothes and saving electricity consumption. Constructed from steel with a gleaming, rust-resistant, chrome finish. Accordion design drops and locks into place; folds flat to 3-inch width for storage. Design allow for clothes and household items to dry draped or laid flat. Measures 41.5"H x 29.5"W x 15"D; limited lifetime warranty', :photo_url => ':https =>//s3.amazonaws.com/store_engine/small/DRY-01234_450px.jpg')
    Product.create!(:store_id => store.id, :featured => false, :active => true, :quantity => "#{(1..500).to_a.sample}".to_i, :name => 'Mesh Pop Open Hamper, Black', :price => 3998.to_f/100, :description => 'Honey-Can-Do HMP-01127 Mesh Pop Open Hamper, Black, Large Hamper. Easily pops-up or down for easy assembly and storage. Mesh material lets clothes breathe. Handy straps for ease in mobility. Limited lifetime warranty. Item dimensions are 19x24-inch', :photo_url => ':https =>//s3.amazonaws.com/store_engine/small/HMP-01127_450px.jpg')
    Product.create!(:store_id => store.id, :featured => false, :active => true, :quantity => "#{(1..500).to_a.sample}".to_i, :name => 'Hanging Closet Organizer, White', :price => 3598.to_f/100, :description => 'Honey-Can-Do SFT-01239 Hanging Closet Organizer, White, 8-Shelf. 8-shelf hanging organizer perfect for clothes, linens, and accessories. Made from durable polyester material, includes 8-reinforced shelves. Attaches directly to any standard closet rod with hook-and-loop closure. Optional storage drawers can be fitted into the shelves. Measures 12-inches wide by 12-inches deep by 54-inches high; limited lifetime warranty', :photo_url => ':https =>//s3.amazonaws.com/store_engine/small/SFT-01239_450px.jpg')
    Product.create!(:store_id => store.id, :featured => false, :active => true, :quantity => "#{(1..500).to_a.sample}".to_i, :name => 'Hanging Shoe Organizer, White', :price => 2798.to_f/100, :description => 'Honey-Can-Do SFT-01240 Hanging Shoe Organizer, White, 10-Shelf. Hanging fabric shoe organizer in white with shelves for 10 pairs of shoes. Made from durable polyester material, includes 10-reinforced shelves. Easily attaches directly to your closet rod with a hook and loop closure. Can be used for more than shoes--great for kids clothes, accessories and more. Measures 6 by 12 by 54-inches; backed by limited lifetime warranty', :photo_url => ':https =>//s3.amazonaws.com/store_engine/small/SFT-01240_450px.jpg')
    Product.create!(:store_id => store.id, :featured => false, :active => true, :quantity => "#{(1..500).to_a.sample}".to_i, :name => 'Over The Door Shoe Organizer, White', :price => 3398.to_f/100, :description => 'Honey-Can-Do SFT-01242 Over The Door Shoe Organizer, White, 24-Pocket. 24-pocket fabric shoe organizer hangs over any standard door or closet rod. Made of sturdy polyester with durable clear nylon pouches. Versatile design also great for storing accessories, craft supplies, and more. Available in several colors to complement any decor. Measures 20-inches wide by 54-inches long; limited lifetime warranty', :photo_url => ':https =>//s3.amazonaws.com/store_engine/small/SFT-01242_450px.jpg')
    Product.create!(:store_id => store.id, :featured => false, :active => true, :quantity => "#{(1..500).to_a.sample}".to_i, :name => 'Heavy-duty Triple Rolling Laundry Sorter/Hamper, Chrome', :price => 20198.to_f/100, :description => 'Honey-Can-Do SRT-01235 Heavy-duty Triple Rolling Laundry Sorter/Hamper, Chrome. Commercial-grade triple laundry sorter combines sleek design and sturdy heavy-duty construction. Rust-resistant chrome-plated steel frame; high-traction, lockable rubber casters. 3 removable white poly-cotton sorting bins with metal handles for easy lifting. Lifetime limited warranty. Measures approximately 31-inches wide by 16-inches deep by 33-inches high', :photo_url => ':https =>//s3.amazonaws.com/store_engine/small/SRT-01235_450px.jpg')
    Product.create!(:store_id => store.id, :featured => false, :active => true, :quantity => "#{(1..500).to_a.sample}".to_i, :name => 'Jersey Cotton Laundry Bag, Blue', :price => 2598.to_f/100, :description => 'Honey-Can-Do LBG-01141 Jersey Cotton Laundry Bag, Blue. Blue laundry bag to keep dirty clothes organized and easy to transport. Sewn from 100 percent jersey cotton for a natural softness and durability. Carrying drawstring with cinch closure to prevent contents from spilling. Available in several colors for fun choices and easy sorting. Measures 24 by 36-inches; comes with a limited lifetime warranty', :photo_url => ':https =>//s3.amazonaws.com/store_engine/small/LBG-01141_450px.jpg')
    Product.create!(:store_id => store.id, :featured => false, :active => true, :quantity => "#{(1..500).to_a.sample}".to_i, :name => 'Mesh Laundry Bag, Blue', :price => 1398.to_f/100, :description => 'Honey-Can-Do LBG-01161 Mesh Laundry Bag, Blue. Premium textile material for long-lasting laundry fun. Carrying draw string prevents contents from spilling. Limited lifetime warranty. Item dimensions are 24 by 36-inch. ', :photo_url => ':https =>//s3.amazonaws.com/store_engine/small/LBG-01161_450px.jpg')
    Product.create!(:store_id => store.id, :featured => false, :active => true, :quantity => "#{(1..500).to_a.sample}".to_i, :name => 'Sweater Wash Bag, White', :price => 1398.to_f/100, :description => 'Honey-Can-Do LBG-01144 Sweater Wash Bag, White. Rustproof zipper. Durable mesh material. Limited lifetime warranty. Item dimensions are 23 by 22-inch. ', :photo_url => ':https =>//s3.amazonaws.com/store_engine/small/LBG-01144_450px.jpg')
    Product.create!(:store_id => store.id, :featured => false, :active => true, :quantity => "#{(1..500).to_a.sample}".to_i, :name => 'Lingerie Wash Bag, White', :price => 998.to_f/100, :description => 'Honey-Can-Do LBG-01145 Lingerie Wash Bag, White. Honey-can-do white lingerie wash bag. Wash your lingerie without damage from the elements. Durable mesh material. Backed by limited lifetime warranty. Item dimensions are 12x18-inches', :photo_url => ':https =>//s3.amazonaws.com/store_engine/small/LBG-01145_450px.jpg')
    Product.create!(:store_id => store.id, :featured => false, :active => true, :quantity => "#{(1..500).to_a.sample}".to_i, :name => 'Hosiery Wash Bag, White', :price => 1598.to_f/100, :description => 'Honey-Can-Do LBG-01146 Hosiery Wash Bag, White, 4-Compartment. Durable mesh material. Limited lifetime warranty. . . ', :photo_url => ':https =>//s3.amazonaws.com/store_engine/small/LBG-01146_450px.jpg')
    Product.create!(:store_id => store.id, :featured => false, :active => true, :quantity => "#{(1..500).to_a.sample}".to_i, :name => 'Bra Wash Bag, White', :price => 1998.to_f/100, :description => 'Honey-Can-Do LBG-01147 Bra Wash Bag, White. Durable mesh material. Limited lifetime warranty. Item dimensions are 7x5-inch. . ', :photo_url => ':https =>//s3.amazonaws.com/store_engine/small/LBG-01147_450px.jpg')
    Product.create!(:store_id => store.id, :featured => false, :active => true, :quantity => "#{(1..500).to_a.sample}".to_i, :name => 'Mesh Wash Bag set (1 sweater/2 lingerie)', :price => 1998.to_f/100, :description => 'Honey-Can-Do LBG-01148 Mesh Wash Bag set (1 sweater/2 lingerie), 3-Pack, 3-Piece. Great value. Includes 1 sweater bag and 2 lingerie bags. Limited lifetime warranty. White mesh. Durable material', :photo_url => ':https =>//s3.amazonaws.com/store_engine/small/LBG-01148_450px.jpg')
    Product.create!(:store_id => store.id, :featured => false, :active => true, :quantity => "#{(1..500).to_a.sample}".to_i, :name => 'Wood Hangers with Non-slip bar, Maple', :price => 6998.to_f/100, :description => 'Honey-Can-Do HNG-01334 Wood Hangers with Non-slip bar, 24-Pack, Maple. Grooved bar- used to hang dresses, blouses, etc.. Sturdy wood construction- Built to hold all shapes and styles of jackets, coats, shirts, etc. Sturdy wood construction to avoid creases and wrinkles. Attractive maple finish. Home organization made easy', :photo_url => ':https =>//s3.amazonaws.com/store_engine/small/HNG-01334_450px.jpg')
    Product.create!(:store_id => store.id, :featured => false, :active => true, :quantity => "#{(1..500).to_a.sample}".to_i, :name => 'Wood Hangers with Non-slip bar, Cherry', :price => 6998.to_f/100, :description => 'Honey-Can-Do HNG-01335 Wood Hangers with Non-slip bar, 24-Pack, Cherry. Grooved bar- used to hang dresses, blouses, etc.. Sturdy wood construction- Built to hold all shapes and styles of jackets, coats, shirts, etc. Sturdy wood construction to avoid creases and wrinkles. Attractive cherry finish. Home organization made easy', :photo_url => ':https =>//s3.amazonaws.com/store_engine/small/HNG-01335_450px.jpg')
    Product.create!(:store_id => store.id, :featured => false, :active => true, :quantity => "#{(1..500).to_a.sample}".to_i, :name => 'Wood Clothespins with Spring', :price => 998.to_f/100, :description => 'Honey-Can-Do DRY-01375 Wood Clothespins with Spring, 50-Pack, 4.75x5. Love drying your clothes naturally but cannot stand finding heavy towels on the ground? search no more. This clothespin will hold up to 10lbs per clip. Rust and moisture resistant, the birch hardwood construction and heavy-duty spring will last through your most challenging laundry days. Pack :qty => 50. Dimensions same as regular :clothespins => 0.5h x 0.4w x 3.3l-inches', :photo_url => ':https =>//s3.amazonaws.com/store_engine/small/DRY-01375_450px.jpg')
    Product.create!(:store_id => store.id, :featured => false, :active => true, :quantity => "#{(1..500).to_a.sample}".to_i, :name => 'Wood Clothespins with Spring', :price => 1398.to_f/100, :description => 'Honey-Can-Do DRY-01376 Wood Clothespins with Spring, 100-Pack, 11.25x6.5. Love drying your clothes naturally but cannot stand finding heavy towels on the ground? search no more. This clothespin will hold up to 10lbs per clip. Rust and moisture resistant, the birch hardwood construction and heavy-duty spring will last through your most challenging laundry days. Pack :qty => 100. Dimensions same as regular :clothespins => 0.5h x 0.4w x 3.3l-inches', :photo_url => ':https =>//s3.amazonaws.com/store_engine/small/DRY-01376_450px.jpg')
    Product.create!(:store_id => store.id, :featured => false, :active => true, :quantity => "#{(1..500).to_a.sample}".to_i, :name => 'Wrapping Paper Organizer, Red', :price => 5198.to_f/100, :description => 'Honey-Can-Do SFT-01598 Wrapping Paper Organizer, Red, 40-Inch. Has a zipper, not velcro. Holds up to 8 rolls of wrapping paper. Handles on top and side for easy lifting. There are 2 large clear pockets on the lid. 4 small compartments at the ends', :photo_url => ':https =>//s3.amazonaws.com/store_engine/small/SFT-01598_450px.jpg')
    Product.create!(:store_id => store.id, :featured => false, :active => true, :quantity => "#{(1..500).to_a.sample}".to_i, :name => 'Kids Storage Organizer', :price => 22998.to_f/100, :description => 'Honey-Can-Do SRT-01602 Kids Storage Organizer, 12-Bins. Removable containers make for quick clean up. Surfaces are durable and stain resistant. Corners are rounded - no sharp edges. Featuring durable strap to secure unit onto wall for safety. Helps develop organization skills', :photo_url => ':https =>//s3.amazonaws.com/store_engine/small/SRT-01602_450px.jpg')
    Product.create!(:store_id => store.id, :featured => false, :active => true, :quantity => "#{(1..500).to_a.sample}".to_i, :name => 'Deluxe Bamboo Shoe Shelf', :price => 11998.to_f/100, :description => 'Honey-Can-Do SHO-01599 Deluxe Bamboo Shoe Shelf, 3-Tier. 3-tier shelf for shoes; approximately 3 feet wide; less than 2 feet high. Made from fast-growing bamboo for reduced environmental impact. Slatted surface is attractive, durable, and naturally moisture resistant. Holds approximately 9 to 12 pairs of adult-size shoes. Wipes clean; easy to assemble; available in 2-tier and 3-tier models', :photo_url => ':https =>//s3.amazonaws.com/store_engine/small/SHO-01599_450px.jpg')
    Product.create!(:store_id => store.id, :featured => false, :active => true, :quantity => "#{(1..500).to_a.sample}".to_i, :name => 'Bamboo Shoe Shelf', :price => 7398.to_f/100, :description => 'Honey-Can-Do SHO-01600 Bamboo Shoe Shelf, 2-Tier. 2-tier shelf for shoes, slippers, and boots; 27-1/2 by 10-1/4 by 15-3/4 inches. Made from fast-growing bamboo for reduced environmental impact. Slatted surface is attractive, durable, and naturally moisture resistant. Holds approximately 6 to 8 pairs of adult-size shoes. Wipes clean; easy to assemble; available in 2-tier and 3-tier models', :photo_url => ':https =>//s3.amazonaws.com/store_engine/small/SHO-01600_450px.jpg')
    Product.create!(:store_id => store.id, :featured => false, :active => true, :quantity => "#{(1..500).to_a.sample}".to_i, :name => 'Kids Storage Organizer, White', :price => 22998.to_f/100, :description => 'Honey-Can-Do SRT-01603 Kids Storage Organizer, White, 12-Bins. Removable containers make for quick clean up. Surfaces are durable and stain resistant. Corners are rounded - no sharp edges. Featuring durable strap to secure unit onto wall for safety. Helps develop organization skills', :photo_url => ':https =>//s3.amazonaws.com/store_engine/small/SRT-01603_450px.jpg')
    Product.create!(:store_id => store.id, :featured => false, :active => true, :quantity => "#{(1..500).to_a.sample}".to_i, :name => 'Heavyduty Gullwing Drying Rack', :price => 7198.to_f/100, :description => 'Honey-Can-Do DRY-01610 Heavyduty Gullwing Drying Rack, 42H x23W. Use a drying rack to save energy. :Color => white. Each wing has dividers for holding things to dry. Comes with 2 pairs of shoe holders. Perfect for outdoor or indoor drying', :photo_url => ':https =>//s3.amazonaws.com/store_engine/small/DRY-01610_450px.jpg')
    Product.create!(:store_id => store.id, :featured => false, :active => true, :quantity => "#{(1..500).to_a.sample}".to_i, :name => 'Quick Dry Shower Tote, 6-Pocket, Blue', :price => 2998.to_f/100, :description => 'Honey-Can-Do SFT-01103 Quick Dry Shower Tote, 6-Pocket, Blue. 6-storage pockets. Breathable mesh fabric. Dries quickly. Great for travel. Shower totes', :photo_url => 'https://s3.amazonaws.com/store_engine/small/SFT-01103_450px.jpg')
  end
end

