# encoding: utf-8
# Autogenerated by the db:seed:dump task
# Do not hesitate to tweak this to your needs


blair = Customer.create(
  :display_name => "blair",
  :email => "blair81@gmail.com",
  :password => "password",
  :password_confirmation => "password",
  :admin => false,
  :first_name => "Blair",
  :last_name => "Anderson" )

logan = Customer.create(
  :display_name => "Logan",
  :email => "lsears322@gmail.com",
  :password => "password",
  :password_confirmation => "password",
  :admin => false,
  :first_name => "Logan",
  :last_name => "Sears" )

chris = Customer.create(
  :display_name => "Chris",
  :email => "rehpotsirhc46@gmail.com",
  :password => "password",
  :password_confirmation => "password",
  :admin => false,
  :first_name => "Chris",
  :last_name => "Knight" )

jen = Customer.create(
  :display_name => "jen",
  :email => "jen7maples@gmail.com",
  :password => "password",
  :password_confirmation => "password",
  :admin => false,
  :first_name => "jen",
  :last_name => "eliuk" )

frank = Customer.create(
  :display_name => "Franklin",
  :email => "demoXX+franklin@jumpstartlab.com",
  :password => "password",
  :password_confirmation => "password",
  :admin => false,
  :first_name => "Franklin ",
  :last_name => "Webber" )

katrina = Customer.create(
  :display_name => "Katrina",
  :email => "demoXX+katrina@jumpstartlab.com",
  :password => "password",
  :password_confirmation => "password",
  :admin => true,
  :first_name => "Katrina",
  :last_name => "Owen" )

customer2 = Customer.create(
  :display_name => "admin",
  :email => "admin@jumpstartlab.com",
  :password => "password",
  :password_confirmation => "password",
  :admin => true,
  :first_name => "admin",
  :last_name => "admin" )

customer3 = Customer.create(
  :display_name => "j3",
  :email => "demoXX+jeff@jumpstartlab.com",
  :password => "password",
  :password_confirmation => "password",
  :admin => false,
  :first_name => "Jeff",
  :last_name => "Casimir")


customer4 = Customer.create(
  :display_name => "SkrilleX",
  :email => "demoXX+steve@jumpstartlab.com",
  :password => "password",
  :password_confirmation => "password",
  :admin => true,
  :first_name => "Steve",
  :last_name => "Klabnik" )

10.times do |i|
  Customer.create(
    :display_name => "random_user#{i}",
    :email => "demoXX+random#{i}@jumpstartlab.com",
    :password => "password",
    :password_confirmation => "password",
    :admin => false,
    :first_name => Faker::Name.first_name,
    :last_name => Faker::Name.last_name )
  puts "creating user #{i}"
end

product_images = [
"https://s3-us-west-2.amazonaws.com/engineproducts/Split_board.jpg",
"https://s3-us-west-2.amazonaws.com/engineproducts/arbor_board.jpg",
"https://s3-us-west-2.amazonaws.com/engineproducts/avalanche_pack.jpg",
"https://s3-us-west-2.amazonaws.com/engineproducts/black_long.jpg",
"https://s3-us-west-2.amazonaws.com/engineproducts/black_pack.jpg",
"https://s3-us-west-2.amazonaws.com/engineproducts/blacker_pack.jpg",
"https://s3-us-west-2.amazonaws.com/engineproducts/blue_ball_pack.jpg",
"https://s3-us-west-2.amazonaws.com/engineproducts/boat_water.jpg",
"https://s3-us-west-2.amazonaws.com/engineproducts/camel_pack.jpg",
"https://s3-us-west-2.amazonaws.com/engineproducts/camp_pack.jpg",
"https://s3-us-west-2.amazonaws.com/engineproducts/flipper_kit.jpg",
"https://s3-us-west-2.amazonaws.com/engineproducts/gloves.jpg",
"https://s3-us-west-2.amazonaws.com/engineproducts/go_pro.jpg",
"https://s3-us-west-2.amazonaws.com/engineproducts/green_boat.jpg",
"https://s3-us-west-2.amazonaws.com/engineproducts/hammock_tent.jpg",
"https://s3-us-west-2.amazonaws.com/engineproducts/king_tent.jpg",
"https://s3-us-west-2.amazonaws.com/engineproducts/miller_paddle.jpg",
"https://s3-us-west-2.amazonaws.com/engineproducts/my_tent.jpg",
"https://s3-us-west-2.amazonaws.com/engineproducts/new_tent.jpg",
"https://s3-us-west-2.amazonaws.com/engineproducts/north_tent.jpg",
"https://s3-us-west-2.amazonaws.com/engineproducts/octi_long.jpg",
"https://s3-us-west-2.amazonaws.com/engineproducts/octi_paddle.jpg",
"https://s3-us-west-2.amazonaws.com/engineproducts/sharp_paddle.jpg",
"https://s3-us-west-2.amazonaws.com/engineproducts/shelter_tent.jpg",
"https://s3-us-west-2.amazonaws.com/engineproducts/sick_goggles.jpg",
"https://s3-us-west-2.amazonaws.com/engineproducts/tech_goggles.jpg",
"https://s3-us-west-2.amazonaws.com/engineproducts/venice_long.jpg",
"https://s3-us-west-2.amazonaws.com/engineproducts/white_goggle.jpg",
"https://s3-us-west-2.amazonaws.com/engineproducts/wood_board.jpg"
]



store_names = [["Slick Bike Shop", "slick-bike-shop"], ["Cool Runnings", "cool-runnings"], ["Cool Sunglasses", "cool-sunglasses"], ["Hotty Threads", "hot-threads"], ["Obigear", "obigear"], ["ObiWear", "obiwear"], ["Panda Pants", "panda-pants"], ["Blairs HotDog Store", "blairs-hotdog-store"], ["Gather", "gather"], ["ToysRUs", "toysrus"]]

store_names.each do |name,path|
  store = Store.create!(name: name, path: path, description: Faker::Lorem.paragraph(1), status:"active")
  Store.include_admin(frank.id, store.id)
  Store.include_admin(blair.id, store.id)
  Store.include_stocker(logan.id, store.id)
  Store.include_stocker(chris.id, store.id)

  print "\ncreating #{store.name}..."
  cats = %w(sunglasses goggles skis snowboards boots helmets gloves backpacks cameras luggage clothing)

  100.times do |i|
    Product.create!(store_id: store.id, name: Faker::Name.name, description: Faker::Lorem.paragraph(3), price: "#{(1..500).to_a.sample}.0".to_f, quantity: "#{(1..500).to_a.sample}".to_i, image_url: product_images.sample, featured: false, active: true, categories_list:cats.sample)
    print "."
  end
end

cart = {1=>1}
store_id = 1
2.times do |i|
  Order.for_customer(frank,cart,store_id)
end

2.times do |i|
  order = Order.for_customer(blair,cart,store_id)
  order.status = "paid"
  order.save
end

2.times do |i|
  order = Order.for_customer(jen,cart,store_id)
  order.status = "shipped"
  order.save
end

2.times do |i|
  order = Order.for_customer(customer3,cart,store_id)
  order.status = "cancelled"
  order.save
end

2.times do |i|
  order = Order.for_customer(katrina,cart,store_id)
  order.status = "returned"
  order.save
end
