# encoding: utf-8
# Autogenerated by the db:seed:dump task
# Do not hesitate to tweak this to your needs

Customer.create([
  { :username => "Franklin", :email => "demoXX+franklin@jumpstartlab.com", :crypted_password => "$2a$10$x2ltEpMymqD/d0CEreVbv.InKmIZ5aPaSvX4QHlzayKjlGxIMpRea", :salt => "x3QXvonoEpakrK7fwa1n", :created_at => "2013-04-04 04:20:53", :updated_at => "2013-04-04 04:25:21", :admin => nil, :first_name => "Franklin ", :last_name => "Webber" },
  { :username => "admin", :email => "admin@jumpstartlab.com", :crypted_password => "$2a$10$PZNVZffKHQLdukHL78K7Q.OIaph9wfWiH0ww50AM/DgwGdDtpUYJ2", :salt => "h7TiXZf2wNxpMiJyFW4a", :created_at => "2013-04-04 04:27:34", :updated_at => "2013-04-04 04:28:50", :admin => true, :first_name => "admin", :last_name => "admin" },
  { :username => "j3", :email => "demoXX+jeff@jumpstartlab.com", :crypted_password => "$2a$10$WZLfP3KibBanTgpsgBDM.eG/nwTJguhATJQFA6IC78s9Y5pZj33d.", :salt => "9rjRvA78x554e1mZuvtY", :created_at => "2013-04-04 04:26:24", :updated_at => "2013-04-04 04:26:24", :admin => nil, :first_name => "Jeff", :last_name => "Casimir" },
  { :username => "Skrillex", :email => "demoXX+steve@jumpstartlab.com", :crypted_password => "$2a$10$PZNVZffKHQLdukHL78K7Q.OIaph9wfWiH0ww50AM/DgwGdDtpUYJ2", :salt => "h7TiXZf2wNxpMiJyFW4a", :created_at => "2013-04-04 04:27:34", :updated_at => "2013-04-04 04:28:50", :admin => true, :first_name => "Steve", :last_name => "Klabnik" }
], :without_protection => true )

store_names = [["Slick Bike Shop", "slick-bike-shop"], ["Cool Runnings", "cool-runnings"], ["Cool Sunglasses", "cool-sunglasses"], ["Hotty Threads", "hot-threads"], ["Obigear", "obigear"], ["ObiWear", "obiwear"], ["Panda Pants", "panda-pants"], ["Blairs HotDog Store", "blairs-hotdog-store"], ["UnGather", "ungather"], ["NotGather", "not-gather"]]

store_names.each do |name,path|
  store = Store.create!(name: name, path: path, description: Faker::Lorem.paragraph(1))
  print "\ncreating #{store.name}..."
  cats = %w(sunglasses glasses hats ice-cream backpacks coffee friends cake chairs whiteboards)
  10.times do |i|
    Product.create!(store_id: store.id, name: Faker::Name.name, description: Faker::Lorem.paragraph(3), price: "#{(1..500).to_a.sample}.0".to_f, quantity: "#{(1..500).to_a.sample}".to_i, featured: false, photo_url: "http://lorempixel.com/600/600", active: true, categories_list:cats[i])
    print "..."
  end
end
